// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoZVcTAdM-yfKhIq11dICsAo02LVWnvp4',
    appId: '1:293044888158:web:47108943761b30c9ec4acf',
    messagingSenderId: '293044888158',
    projectId: 'supply-supplier-app',
    authDomain: 'supply-supplier-app.firebaseapp.com',
    storageBucket: 'supply-supplier-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCepDdQgDwGMQ1WEjMJQ4GiQ2qcQTlD3qQ',
    appId: '1:293044888158:android:e9e058cb5b6a9f98ec4acf',
    messagingSenderId: '293044888158',
    projectId: 'supply-supplier-app',
    storageBucket: 'supply-supplier-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpF6n_9VmLCQqNw_i1kqedGuZQdsj6cTc',
    appId: '1:293044888158:ios:a37688903d4eac3aec4acf',
    messagingSenderId: '293044888158',
    projectId: 'supply-supplier-app',
    storageBucket: 'supply-supplier-app.appspot.com',
    iosBundleId: 'com.example.supplyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpF6n_9VmLCQqNw_i1kqedGuZQdsj6cTc',
    appId: '1:293044888158:ios:30fea26289ac1e0cec4acf',
    messagingSenderId: '293044888158',
    projectId: 'supply-supplier-app',
    storageBucket: 'supply-supplier-app.appspot.com',
    iosBundleId: 'com.example.supplyApp.RunnerTests',
  );
}
